# Site settings
title: "juwon"
email: juwon2055@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
#   supported by <a href = "https://blog.jcy1511.com"> 심인고 2-3 장찬영</a> 
# baseurl: "/urban-theme" # the subpath of your site, e.g. /blog
url: "https://juwon2055.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
instagram_username: wndnjsx_x

# Build settings
markdown: kramdown
permalink: pretty
timezone: "Asia/Seoul"